apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspectdns
  labels:
    app: inspectdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspectdns
  template:
    metadata:
      labels:
        app: inspectdns
    spec:
      containers:
        - name: inspectdns
          image: "username/inspectdns:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
