apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspecthttp
  labels:
    app: inspecthttp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspecthttp
  template:
    metadata:
      labels:
        app: inspecthttp
    spec:
      containers:
        - name: inspecthttp
          image: "username/inspecthttp:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
